-- Create the schema
CREATE DATABASE IF NOT EXISTS Cybersecurity_Log;
USE Cybersecurity_Log;

CREATE TABLE INCIDENT (
    IncidentID VARCHAR(20) NOT NULL,
    CreatedTimestamp DATETIME NOT NULL,
    ReportedBySource VARCHAR(128) NULL,
    Status VARCHAR(20) NOT NULL,
    Severity VARCHAR(20) NOT NULL,
    ParentIncidentID VARCHAR(20) NULL,
    CONSTRAINT PK_INCIDENT PRIMARY KEY (IncidentID),
    CONSTRAINT FK_INCIDENT_PARENT FOREIGN KEY (ParentIncidentID)
        REFERENCES INCIDENT (IncidentID)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT CHK_INCIDENT_STATUS CHECK (Status IN ('Open', 'In Progress', 'Closed')),
    CONSTRAINT CHK_INCIDENT_SEVERITY CHECK (Severity IN ('Low', 'Medium', 'High', 'Critical')),
    CONSTRAINT CHK_INCIDENT_CREATED CHECK (CreatedTimestamp >= '2000-01-01 00:00:00')
);

CREATE TABLE ASSET_IDENTITY (
    AssetID VARCHAR(64) NOT NULL,
    LifecycleState VARCHAR(20) NOT NULL,
    AssetLabel VARCHAR(255) NOT NULL,
    AssetType VARCHAR(32) NOT NULL,
    Justification VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ASSET_IDENTITY PRIMARY KEY (AssetID),
    CONSTRAINT CHK_ASSET_LIFECYCLE CHECK (LifecycleState IN ('Observed', 'Blocked', 'Protected')),
    CONSTRAINT CHK_ASSET_TYPE CHECK (AssetType IN ('ExternalSource', 'ProtectedService', 'InternalHost')),
    CONSTRAINT CHK_ASSET_LABEL CHECK (AssetLabel <> ''),
    CONSTRAINT CHK_ASSET_JUST CHECK (Justification <> '')
);

CREATE TABLE ALERT_EVENT (
    SourceSystem VARCHAR(64) NOT NULL,
    SourceEventID VARCHAR(32) NOT NULL,
    EventTimestamp DATETIME NOT NULL,
    RawSummary VARCHAR(512) NOT NULL,
    IncidentID VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ALERT_EVENT PRIMARY KEY (SourceSystem, SourceEventID),
    CONSTRAINT FK_ALERT_INCIDENT FOREIGN KEY (IncidentID)
        REFERENCES INCIDENT (IncidentID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CHK_ALERT_SOURCE CHECK (SourceSystem <> ''),
    CONSTRAINT CHK_ALERT_EVENTTIME CHECK (EventTimestamp >= '2000-01-01 00:00:00'),
    CONSTRAINT CHK_ALERT_SUMMARY CHECK (RawSummary <> '')
);

CREATE TABLE IOC (
    IOCType VARCHAR(20) NOT NULL,
    IOCValue VARCHAR(255) NOT NULL,
    FirstSeen DATETIME NOT NULL,
    LastSeen DATETIME NOT NULL,
    IncidentID VARCHAR(20) NOT NULL,
    CONSTRAINT PK_IOC PRIMARY KEY (IOCType, IOCValue),
    CONSTRAINT FK_IOC_INCIDENT FOREIGN KEY (IncidentID)
        REFERENCES INCIDENT (IncidentID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT CHK_IOC_TYPE CHECK (IOCType IN ('ip', 'domain', 'url', 'hash')),
    CONSTRAINT CHK_IOC_VALUE CHECK (IOCValue <> ''),
    CONSTRAINT CHK_IOC_TIMES CHECK (FirstSeen <= LastSeen)
);

CREATE TABLE INCIDENT_ASSET (
    IncidentID VARCHAR(20) NOT NULL,
    AssetID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_INCIDENT_ASSET PRIMARY KEY (IncidentID, AssetID),
    CONSTRAINT FK_IA_INCIDENT FOREIGN KEY (IncidentID)
        REFERENCES INCIDENT (IncidentID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_IA_ASSET FOREIGN KEY (AssetID)
        REFERENCES ASSET_IDENTITY (AssetID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE RESPONSE_ACTION (
    ActionID VARCHAR(20) NOT NULL,
    Owner VARCHAR(64) NOT NULL,
    DueDate DATETIME NOT NULL,
    Status VARCHAR(20) NOT NULL,
    IncidentID VARCHAR(20) NOT NULL,
    CONSTRAINT PK_RESPONSE_ACTION PRIMARY KEY (ActionID),
    CONSTRAINT FK_ACTION_INCIDENT FOREIGN KEY (IncidentID)
        REFERENCES INCIDENT (IncidentID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CHK_ACTION_OWNER CHECK (Owner <> ''),
    CONSTRAINT CHK_ACTION_STATUS CHECK (Status IN ('Open', 'In Progress', 'Done')),
    CONSTRAINT CHK_ACTION_DUE CHECK (DueDate >= '2000-01-01 00:00:00')
);

CREATE TABLE EVIDENCE (
    EvidenceID VARCHAR(20) NOT NULL,
    StorageLocation VARCHAR(255) NOT NULL,
    CollectedBy VARCHAR(64) NOT NULL,
    CollectedAt DATETIME NOT NULL,
    IntegrityHash CHAR(64) NOT NULL,
    IncidentID VARCHAR(20) NOT NULL,
    CONSTRAINT PK_EVIDENCE PRIMARY KEY (EvidenceID),
    CONSTRAINT FK_EVIDENCE_INCIDENT FOREIGN KEY (IncidentID)
        REFERENCES INCIDENT (IncidentID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT CHK_EVIDENCE_STORAGE CHECK (StorageLocation <> ''),
    CONSTRAINT CHK_EVIDENCE_COLLECTED CHECK (CollectedAt >= '2000-01-01 00:00:00'),
    CONSTRAINT CHK_EVIDENCE_HASH CHECK (CHAR_LENGTH(IntegrityHash) = 64)
);